### ISSUE TITLE
"Sonic 2 & Knuckles" black screen

### ISSUE THREAD

**Issue by ThreepwoodLeBrush** [MiSTer-devel/Genesis_MiSTer#145]
When trying to load the ROM of the combined games "Sonic the Hedgehog 2" and "Sonic & Knuckles" the screen stays black and the game does not run. The same ROM works fine in the emulator Fusion364.

**Comment by elexor** [comment]
Works for me please check your rom.

**Comment by ThreepwoodLeBrush** [comment]
Already checked the ROM and confirmed the checksum to be correct (CRC32 2AC1E7C6). I dumped it myself from working carts. I am on the latest Genesis core version (02.07.01) and tried two different MiSTers.

(My "Sonic 3 & Knuckles" and "Blue Sphere" work)

**Comment by elexor** [comment]
I think it requires an everdrive fix to work.

**Comment by elexor** [comment]
The problem is that the original Sonic & Knuckles cartridge had a special custom chip in it called the UPMEM chip at a rom size of 256 kilobytes that when locked-on to Sonic 2 it would memorize the game's functions and data with Sonic & Knuckles, it's something the Mega EverDrive cannot play normally as downloading the ''Knuckles In Sonic 2'' rom from any download site does not have the custom chip digitally emulated in it.

**Comment by ThreepwoodLeBrush** [comment]
Thanks a lot, Elexor, that will be the issue. I guess Fusion346 has that chip emulated. Guess there is no issue to fix as this affects only one game. Closing and thanks again!
