### ISSUE TITLE
Please add CRT horizontal and vertical position adjustment ：）  

### ISSUE THREAD

**Issue by maxxsun** [MiSTer-devel/Genesis_MiSTer#178]
Please add CRT horizontal and vertical position adjustment ：）  Thank you very much！

**Comment by sorgelig** [comment]
OMG... Arcade crap  option on a good core? No way!

**Comment by sorgelig** [comment]
Get a normal TV.

**Comment by ArcadeHustle** [comment]
@sorgelig I am confused is #MiSTercade an "official" project accessory? There are many people pushing for JAMMA support these days. Are you against this? Do you not want people to use JAMMA edge Addons? We kind of will always be using CRTs in this situation.  
https://misteraddons.com/products/mistercade
[![Mistercade](http://img.youtube.com/vi/rmassx9hJP8/0.jpg)](https://www.youtube.com/watch?v=rmassx9hJP8)

**Comment by Blitzwing1** [comment]
> @sorgelig I am confused is #MiSTercade an "official" project accessory? There are many people pushing for JAMMA support these days. Are you against this? Do you not want people to use JAMMA edge Addons? We kind of will always be using CRTs in this situation.  
> https://misteraddons.com/products/mistercade
> [![Mistercade](http://img.youtube.com/vi/rmassx9hJP8/0.jpg)](https://www.youtube.com/watch?v=rmassx9hJP8)
> 
> 

Most Arcade cores have options for vertical and horizontal adjustment for them already, with those adjustment can be necessary. This was asking for it to be added to the genesis core, consoles were designed with TVs in mind, if they are out of alignment then the problem is likely to be on the TV end and adjustment should be performed there.

Unless I'm very much mistaken Mistercade is unofficial.

**Comment by ArcadeHustle** [comment]
@Blitzwing1 I guess anything not on this list isn't "official" just the same. https://github.com/MiSTer-devel/Hardware_MiSTer

I'm primarily asking because it is weird to expect there to be a large push for "arcade" support in the community, and expect arcade users to intentionally avoid "console" cores, and only ply "arcade" cores. Perhaps @sorgelig can make a proper statement on his opinion of "arcade" support. Should we expect all duplications of accuracy to be USB+HDMI+LCD TV based experiences? I would like to use the NES core for example to replace some of my Nintendo VS boards that are aging, should I expect the same response if I ask? The genesis core can play "Megaplay" games by Sega, yes? So the crossover between console and arcade core is obviously blurry, even in this case. https://segaretro.org/Mega_Play

**Comment by Blitzwing1** [comment]
In the RetroRGB video you referenced he plays console versions of Arcade games, as long as the "monitor" you're using is a consumer grade (625/525 line) TV then those console cores should have little to no issue with alignment, any large deviation is likely an issue elsewhere that's the point I was making. An arcade TTL screen or VGA CRT monitor is another issue but, and that is what the "vga_scaler" option is for.

I can't speak for sorgelig or any other developer and maintainer.

**Comment by sorgelig** [comment]
It's ok to have it in arcades as many original arcades aren't based on TV and had little variations. Also arcades are not always precisely follow original schematics.
Console cores are opposite - they carefully developed to follow the original TV timings. So they don't need such adjustments.
MiSTercade is not official addon. 
All HW addon't are in MiSTer-devel. Everything else is not official.

**Comment by sorgelig** [comment]
Generally speaking, all arcades originally should be tweaked to a common position, so such option won't be required.

**Comment by ArcadeHustle** [comment]
Generally speaking, all cores should be able to be tweaked, because the reality is such a common position won't happen every time. 

Consider using the open source from Jotego? Would you accept a PR if someone submitted it?  
https://github.com/jotego/jtframe/blob/master/hdl/video/jtframe_resync.v

"CRT H/V adjustment can probably be added to most #MiSTerFPGA codes by instantiating this module in them. Feel free to use it." 
https://twitter.com/topapate/status/1391115446515126273

"In fact, this is the module I use in all my cores."
https://twitter.com/topapate/status/1391118217712701440

**Comment by sorgelig** [comment]
I didn't say i cannot implement it.
I've said it's unneeded option for well developed core.

**Comment by ArcadeHustle** [comment]
Exactly, not that you "cannot", that you "will not". Either that or you are saying this core is not well developed, alongside a few others?

**Comment by ArcadeHustle** [comment]
@Blitzwing1 telling the dude to "Get a normal TV" wasn't !needed! either, am I right?

**Comment by Blitzwing1** [comment]
> @Blitzwing1 telling the dude to "Get a normal TV" wasn't !needed! either, am I right?

Nothing to do with me that's between them. As for your other comment pointing to that just comes across as trolling. You are owed nothing of anyone's free time, there was no sale (by the MiSTer project), no warranty, everything is done freely and everybody can contribute if they have the skills. Learn HDL and do it yourself.

**Comment by ArcadeHustle** [comment]
As far as my other comment, that is nothing to do with you, that is between them and I, I guess? "Nobody has to act on requests that are not !needed!" and directing me to Discord was hardly productive. No one here is acting like they are "owed" anything, you are simply being overly defensive for literally no reason. I don't even know why you are here commenting TBH, are you even a dev involved in this feature request? 

I also don't get how you are going to lead in with "Lastly GitHub is not the place for feature requests", call me a troll, and end on "Lastly GitHub is not the place for feature requests", ok dude I'll just go buy a Raspberry Pi I guess. "You are owed nothing of anyone's free time" you really watch too much Willy Wonka dude. Me thinks you are the one here trolling folks that have a legit problem that they were looking for an answer to. 

"Go buy a new TV" isn't an acceptable answer, and apparently pointing to already working code isn't either. I"ll go start learning HDL, thanks for the suggestion. 

[![wonka](http://img.youtube.com/vi/M5QGkOGZubQ/0.jpg)](https://www.youtube.com/watch?v= M5QGkOGZubQ)

**Comment by paulb-nl** [comment]
These console cores like SNES / Genesis don't need adjustments. They are the reference to which you should adjust your CRT. 

The arcade cores should be tweaked to match the centering of the console cores.

Sometimes arcade cores use too much of the overscan and HV offset options are needed to decide what part of the screen to cut off. That's why I added HV options to the Irem M62 core for example.

**Comment by Blitzwing1** [comment]
> As far as my other comment, that is nothing to do with you, that is between them and I, I guess? "Nobody has to act on requests that are not !needed!" and directing me to Discord was hardly productive. No one here is acting like they are "owed" anything, you are simply being overly defensive for literally no reason. I don't even know why you are here commenting TBH, are you even a dev involved in this feature request? 
> 
> I also don't get how you are going to lead in with "Lastly GitHub is not the place for feature requests", call me a troll, and end on "Learn HDL and do it yourself", ok dude I'll just go buy a Raspberry Pi I guess. "You are owed nothing of anyone's free time" you really watch too much Willy Wonka dude. Me thinks you are the one here trolling folks that have a legit problem that they were looking for an answer to. 
> 
> "Go buy a new TV" isn't an acceptable answer, and apparently pointing to already working code isn't either. I"ll go start learning HDL, thanks for the suggestion. 
> 
> [![wonka](http://img.youtube.com/vi/M5QGkOGZubQ/0.jpg)](https://www.youtube.com/watch?v=M5QGkOGZubQ)
> 

Why are you here? the op isn't even here after being told No. 

No I'm not a developer of this core, but I'll do what I like responding to people who clearly didn't like the answer "no" and carry on like they are owed something. 

Anyway you've had another Dev saying exactly why it isn't needed. That's three of us now two MiSTer Devs and a random.

**Comment by ArcadeHustle** [comment]
"Why are you here? the op isn't even here after being told No.

No I'm not a developer of this core, but I'll do what I like responding to people who clearly didn't like the answer "no" and carry on like they are owed something.

Anyway you've had another Dev saying exactly why it isn't needed. That's three of us now two MiSTer Devs and a random." 

Thanks for showing how welcoming the community is @Blitzwing1

**Comment by Blitzwing1** [comment]
I don't know why you felt the need to reply to a post I intentionally deleted because I didn't like what I wrote! 

I'm not an ambassador for the MiSTer community, so please don't see the interaction with me as some sort of stain on the community as a whole, in my experience it has been welcoming.

On the other side though both needlessly responding to a comment that I deleted and your inability to not heed the words "no" "isn't needed" and carrying on anyway hasn't shown you in the best light either. Most people just shrug and say "oh well, I'll do without"

**Comment by ArcadeHustle** [comment]
I didn't like what you wrote either, and you are indeed a shining microcosm of the community. Thanks for stopping by. Most people IN YOUR situation, just shrug and say <literally nothing> and move on to the next GitHub comment. You however needed to browbeat. Cheers to that.

**Comment by ArcadeHustle** [comment]
"Point being neither of us has acted decently here" no, the point was some folks have CRT behavior that deviates from standard, instead of telling them to buy a new TV, it would be nice if the simple code referenced above was a thing. https://github.com/jotego/jtframe/blob/master/hdl/video/jtframe_resync.v

I will both go buy a raspi, and study HDL in the mean time. Thanks again for the tips!

**Comment by mrchrisster** [comment]
My position pot on my CRT is broken, horizontal adjustment options would be highly appreciated
