### ISSUE TITLE
Another World / Out Of This World Graphical Glitches

### ISSUE THREAD

**Issue by davedoc1984** [MiSTer-devel/Genesis_MiSTer#203]
The Top section of the screen in Another World (E) is glitched and shows a flashing black bar through-out gameplay. This does not happen on real hardware.

**Comment by birdybro** [comment]
This happens on Genesis Plus GX as well which led me to look a little deeper, and it turns out this is a multi-region game. When Playing European games set your region priority to EU>US>JP to make sure that European games load into EU region. When the game is played as PAL, everything works normally.
