### ISSUE TITLE
[audio] Tempo is too slow in Contra: Hard Corps, Castlevania: Bloodlines, konami music engine games

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/Genesis_MiSTer#58]
Hello! :) As the title describes, the tempo of 2 of the songs in Contra: Hard Corps is just a bit too slow. It's pretty easy to miss, and in fact I wasn't sure there was an issue until I broke out my model 1 and 2 Genesis and compared them direct to the MiSTer.

I also found a recording on youtube that demonstrates the correct tempo:
https://youtu.be/1velVMs7vqM?t=1055

Thanks!

EDIT: Also, I made sure that my region was not changed to EU. My region was set to US in the menu, and I disabled the region detector. I also loaded the US Contra: Hard Corps game, and used the same ROM in a Mega Everdrive X7 on my Genesis consoles to test

**Comment by jotego** [comment]
Are you sure you are just not running the PAL version of the console? That
will slow down the tempo.

**Comment by MP2E** [comment]
Yep! Sure did. I disabled region detection, set it to US, and am playing the US copy. I also made sure to use the same rom to compare on an everdrive with console.

**Comment by jotego** [comment]
Then, @sorgelig I think this one is for you. It is likely to be related to system-level timing. Contra may not be using the YM2612 interrupts but relying on some CPU-based clocking. Which CPU? I don't know. It may even be the 68k
@MP2E if you could record your actual console on video, just to remove any level of skepticism we as developers may have. The recording on youtube could have come from an emulator. 
Thanks a lot for reporting this!

**Comment by James-F2** [comment]
MiSTer on top.
Real Genesis Bottom.

![mister ym2612](https://user-images.githubusercontent.com/31185814/59548035-936c9300-8f51-11e9-9ab3-a7ba88004937.png)

**Comment by jotego** [comment]
It is a 3% difference. It's not the regional setting (which would 20%). I cannot help any more. This is a system-level issue.

**Comment by James-F2** [comment]
Yes, very strange.
Other games do not go out of sync and match the original.

**Comment by James-F2** [comment]
Are all the clocks accurate?

**Comment by James-F2** [comment]
Update;
When creating a rom using VGM Player 3.42 from the vgz files, the tempo is correct.

**Comment by jotego** [comment]
The VGM player uses a fixed 44kHz time slice. I am not sure how it keeps
the rythm but it will be the same for all games as audio commands are
sampled at the said 44kHz rate. The internal music driver of the Contra
game must be keeping the rythm in a way that is not accurate in MiST(er).

**Comment by MP2E** [comment]
I did a bit more investigation into this and the sound engine in Contra: Hard Corps is identified as having the "Vampire Killer" music engine. Castlevania: Bloodlines also has this engine as do a few other games listed here:

http://gdri.smspower.org/wiki/index.php/Mega_Drive/Genesis_Sound_Engine_List

It turns out, Castlevania: Bloodlines also has this issue!
https://cdn.discordapp.com/attachments/497145588446396416/611396388349280272/bloodlines_genesis.flac
https://cdn.discordapp.com/attachments/497145588446396416/611396392849506324/bloodlines_mister.flac

This leads me to suspect that the Konami games sharing this music engine likely all have to same bug

**Comment by steven-a-wilson** [comment]
As far as I can tell (not a Genesis or YM2612 guru; learning this as I go), the engine internally keeps time solely by waiting for and then resetting the YM2612 "A" timer with the period registers 'h24/25 set to 'h91/00. If the documentation I've found is correct and I've done the math right, this translates to:

91/00 => 10'b1001000100 = 580
1024 - 580 = 444 ticks per overflow
444 * 18 microseconds/tick = 7992 microseconds
1/7992 microseconds = 125.125... Hz

It may be that the intended interval is exactly 8 ms / 125 Hz, with the timer period being reduced slightly to account for the time taken to reset the timer after exiting the wait loop.

Apart from a bug related to the timers themselves, it seems like this problem could be caused by anything that stops or slows down the Z80 too much. If the timer overflows before the engine is waiting for it (or while in the wait loop, but halted due to 68K holding the bus), I don't think it has any way to "catch up" to the correct time.

Castlevania, at least, seems to hold the Z80 bus while doing certain writes to the VDP. I'm not sure why it does this, but it does suggest the possibility of 68K/VDP timing being involved.

**Comment by greyrogue** [comment]
Good description, steven-a-wilson.  I think I figured it out based on your research.
https://github.com/jotego/jt12/pull/43

**Comment by MP2E** [comment]
Thank you very much both @steven-a-wilson and @greyrogue 

I can confirm this fully fixes the issues

**Comment by MP2E** [comment]
addressed by #79

**Comment by jotego** [comment]
@greyrogue thanks a lot for fixing this. I should have actually thought of the timers because when I was developing JT12 Castlevania was one of the few games that used the timers and I used it to verify them. I obviously misscalibrated it by 1. Very well spotted indeed, thanks!
